/**
 * cashbook REST API
 * API to communicate with cashbook!
 *
 * OpenAPI spec version: 1.0
 * Contact: pascal.wild@mallorca-software.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CashbookAmountDto } from './cashbookAmountDto';
import { CashbookEntryDto } from './cashbookEntryDto';


export interface CashbookDto { 
    beginAmount?: number;
    cashbookAmount?: CashbookAmountDto;
    cashbookEntries?: Array<CashbookEntryDto>;
    expenseCashbookEntries?: Array<CashbookEntryDto>;
    id?: number;
    name?: string;
    revenueCashbookEntries?: Array<CashbookEntryDto>;
}
