/**
 * cashbook REST API
 * API to communicate with cashbook!
 *
 * OpenAPI spec version: 1.0
 * Contact: pascal.wild@mallorca-software.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserDto { 
    email?: string;
    firstName?: string;
    id?: number;
    lastName?: string;
    plainPassword?: string;
    plainPasswordRepeat?: string;
    username?: string;
}
