/**
 * cashbook REST API
 * API to communicate with cashbook!
 *
 * OpenAPI spec version: 1.0
 * Contact: pascal.wild@mallorca-software.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { CashbookDto } from '../model/cashbookDto';
import { CashbookEntryDto } from '../model/cashbookEntryDto';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class CashbookEntryControllerService {

    protected basePath = 'http://cashbook.api.mallorca-software.com';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {

        if (configuration) {
            this.configuration = configuration;
            this.configuration.basePath = configuration.basePath || basePath || this.basePath;

        } else {
            this.configuration.basePath = basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * deleteCashbookEntry
     * 
     * @param cashbookId cashbookId
     * @param cashbookEntryId cashbookEntryId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public deleteCashbookEntryUsingDELETE(cashbookId: number, cashbookEntryId: number, observe?: 'body', reportProgress?: boolean): Observable<CashbookDto>;
    public deleteCashbookEntryUsingDELETE(cashbookId: number, cashbookEntryId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CashbookDto>>;
    public deleteCashbookEntryUsingDELETE(cashbookId: number, cashbookEntryId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CashbookDto>>;
    public deleteCashbookEntryUsingDELETE(cashbookId: number, cashbookEntryId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (cashbookId === null || cashbookId === undefined) {
            throw new Error('Required parameter cashbookId was null or undefined when calling deleteCashbookEntryUsingDELETE.');
        }
        if (cashbookEntryId === null || cashbookEntryId === undefined) {
            throw new Error('Required parameter cashbookEntryId was null or undefined when calling deleteCashbookEntryUsingDELETE.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.delete<CashbookDto>(`${this.configuration.basePath}/api/cashbooks/${encodeURIComponent(String(cashbookId))}/cashbookEntries/${encodeURIComponent(String(cashbookEntryId))}`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * getCashbookEntries
     * 
     * @param cashbookId cashbookId
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public getCashbookEntriesUsingGET(cashbookId: number, observe?: 'body', reportProgress?: boolean): Observable<Array<CashbookEntryDto>>;
    public getCashbookEntriesUsingGET(cashbookId: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<CashbookEntryDto>>>;
    public getCashbookEntriesUsingGET(cashbookId: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<CashbookEntryDto>>>;
    public getCashbookEntriesUsingGET(cashbookId: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (cashbookId === null || cashbookId === undefined) {
            throw new Error('Required parameter cashbookId was null or undefined when calling getCashbookEntriesUsingGET.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            '*/*'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<CashbookEntryDto>>(`${this.configuration.basePath}/api/cashbooks/${encodeURIComponent(String(cashbookId))}/cashbookEntries`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * saveCashbookEntry
     * 
     * @param cashbookId cashbookId
     * @param cashbookEntryDto cashbookEntryDto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public saveCashbookEntryUsingPOST(cashbookId: number, cashbookEntryDto: CashbookEntryDto, observe?: 'body', reportProgress?: boolean): Observable<CashbookDto>;
    public saveCashbookEntryUsingPOST(cashbookId: number, cashbookEntryDto: CashbookEntryDto, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<CashbookDto>>;
    public saveCashbookEntryUsingPOST(cashbookId: number, cashbookEntryDto: CashbookEntryDto, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<CashbookDto>>;
    public saveCashbookEntryUsingPOST(cashbookId: number, cashbookEntryDto: CashbookEntryDto, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {
        if (cashbookId === null || cashbookId === undefined) {
            throw new Error('Required parameter cashbookId was null or undefined when calling saveCashbookEntryUsingPOST.');
        }
        if (cashbookEntryDto === null || cashbookEntryDto === undefined) {
            throw new Error('Required parameter cashbookEntryDto was null or undefined when calling saveCashbookEntryUsingPOST.');
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected !== undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/json'
        ];
        const httpContentTypeSelected: string | undefined = this.configuration.selectHeaderContentType(consumes);
        if (httpContentTypeSelected !== undefined) {
            headers = headers.set('Content-Type', httpContentTypeSelected);
        }

        return this.httpClient.post<CashbookDto>(`${this.configuration.basePath}/api/cashbooks/${encodeURIComponent(String(cashbookId))}/cashbookEntries`,
            cashbookEntryDto,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
